apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    release: prometheus
  name: vote-application-down
spec:
  groups:
    - name: application-status.rules
      rules:
        - alert: VoteApplicationUnreachable
          expr: probe_success{job="blackbox-exporter-prometheus-blackbox-exporter", instance="vote-service.application.svc.cluster.local"} == 0
          for: 5m
          annotations: 
            summary: "Instance {{ $labels.instance }} unreachable"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been unreachable for more than 5 minutes."
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    release: prometheus
  name: result-application-down
spec:
  groups:
    - name: application-status.rules
      rules:
        - alert: ResultApplicationUnreachable
          expr: probe_success{job="blackbox-exporter-prometheus-blackbox-exporter", instance="result-service.application.svc.cluster.local"} == 0
          for: 5m
          annotations: 
            summary: "Instance {{ $labels.instance }} unreachable"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been unreachable for more than 5 minutes."
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    release: prometheus
  name: kafka-redis-consumer-down
spec:
  groups:
    - name: application-status.rules
      rules:
        - alert: KafkaRedisConsumerUnreachable
          expr: probe_success{job="blackbox-exporter-prometheus-blackbox-exporter", instance="kafka-redis-consumer-service.application.svc.cluster.local"} == 0
          for: 5m
          annotations: 
            summary: "Instance {{ $labels.instance }} unreachable"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been unreachable for more than 5 minutes."
