apiVersion: v1
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    metadata:
      annotations:
        meta.helm.sh/release-name: prometheus
        meta.helm.sh/release-namespace: prometheus
      creationTimestamp: "2023-03-24T19:40:59Z"
      generation: 1
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 45.7.1
        chart: kube-prometheus-stack-45.7.1
        heritage: Helm
        release: prometheus
      name: prometheus-kube-prometheus-alertmanager
      namespace: prometheus
      resourceVersion: "669967"
      uid: 4cc68de0-f5ec-4e65-9ec3-cab8d2b6fe1b
    spec:
      alertmanagerConfigNamespaceSelector: {}
      alertmanagerConfigSelector:
        matchLabels:
          alertmanagerConfig: default
      externalUrl: http://prometheus-kube-prometheus-alertmanager.prometheus:9093
      image: quay.io/prometheus/alertmanager:v0.25.0
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      paused: false
      portName: http-web
      replicas: 1
      retention: 120h
      routePrefix: /
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: prometheus-kube-prometheus-alertmanager
      version: v0.25.0
    status:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: "2023-03-28T07:29:38Z"
          observedGeneration: 1
          status: "True"
          type: Available
        - lastTransitionTime: "2023-03-28T07:29:02Z"
          observedGeneration: 1
          status: "True"
          type: Reconciled
      paused: false
      replicas: 1
      unavailableReplicas: 0
      updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
