apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-application-issuer
  namespace: application
spec:
  acme:
    email: antoine.le-guillou@epitech.eu
    # We use the staging server here for testing to avoid hitting
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: example-issuer-account-key
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-prometheus-issuer
  namespace: prometheus
spec:
  acme:
    email: antoine.le-guillou@epitech.eu
    # We use the staging server here for testing to avoid hitting
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: example-issuer-account-key
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik
---

