apiVersion: v1
kind: Namespace
metadata:
  name: sla
---
apiVersion: v1
kind: Secret
metadata:
  name: developers-sa-sla-secret
  namespace: sla
  annotations:
    kubernetes.io/service-account.name: developers-sa-sla
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developers-sa-sla
  namespace: sla
secrets:
  - name: developers-sa-sla-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
  namespace: sla
rules:
  - apiGroups:
      [
        "",
        "apps",
        "batch",
        "autoscaling",
        "apiextensions.k8s.io",
        "rbac.authorization.k8s.io",
        "networking.k8s.io",
        "longhorn.io",
        "storage.k8s.io",
      ]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers
  namespace: sla
subjects:
  - kind: ServiceAccount
    name: developers-sa-sla
    namespace: sla
roleRef:
  kind: Role
  name: developers
  apiGroup: rbac.authorization.k8s.io
---

