# kafka-redis-consumer ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-redis-consumer-configmap
data:
  kafka_brokers: "kafka-cluster-kafka-bootstrap.kafka-operator-system.svc.cluster.local:9092"
  kafka_consumer_group_id: "kafka-redis-consumer-group"
  kafka_topic: votes
  redis_watched_key: votes
  redis_port: "6379"
---
# kafka-redis-consumer ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kafka-redis-consumer-secrets
data:
  # redis-cluster-leader-headless.redis-operator.svc.cluster.local
  redis_host: cmVkaXMtY2x1c3Rlci1sZWFkZXItaGVhZGxlc3MucmVkaXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWw=
  # Nc89JggdSC1I180
  redis_password: TmM4OUpnZ2RTQzFJMTgw
  # redis://:Nc89JggdSC1I180@redis-cluster-leader-headless.redis-operator.svc.cluster.local:6379/0
  redis_cluster_uri: cmVkaXM6Ly86TmM4OUpnZ2RTQzFJMTgwQHJlZGlzLWNsdXN0ZXItbGVhZGVyLWhlYWRsZXNzLnJlZGlzLW9wZXJhdG9yLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMA==
  # postgres://root:dgwjWYtiuXeaRFTmMlxOTrEVyKK8XCKK8dYUUwd3yBQplVwlrWq2W56tp1JX37sG@epitech-postgresql.postgres-operator-system.svc.cluster.local/postgres
  postgres_uri: cG9zdGdyZXM6Ly9yb290OmRnd2pXWXRpdVhlYVJGVG1NbHhPVHJFVnlLSzhYQ0tLOGRZVVV3ZDN5QlFwbFZ3bHJXcTJXNTZ0cDFKWDM3c0dAZXBpdGVjaC1wb3N0Z3Jlc3FsLnBvc3RncmVzLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbC9wb3N0Z3Jlcw==
  # root
  postgres_user: cm9vdA==
  # epitech-postgresql.postgres-operator-system.svc.cluster.local
  postgres_host: ZXBpdGVjaC1wb3N0Z3Jlc3FsLnBvc3RncmVzLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  # postgres
  postgres_db: cG9zdGdyZXM=
  # dgwjWYtiuXeaRFTmMlxOTrEVyKK8XCKK8dYUUwd3yBQplVwlrWq2W56tp1JX37sG
  postgres_password: ZGd3aldZdGl1WGVhUkZUbU1seE9UckVWeUtLOFhDS0s4ZFlVVXdkM3lCUXBsVndscldxMlc1NnRwMUpYMzdzRw==
  # 5432
  postgres_port: NTQzMg==
---
# kafka-redis-consumer DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-redis-consumer-deployment
  labels:
    tier: kafka-redis-consumer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      tier: kafka-redis-consumer
  template:
    metadata:
      labels:
        tier: kafka-redis-consumer
    spec:
      containers:
        - name: kafka-redis-consumer
          image: antoineleguillou/kafka-redis-consumer:20230417.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 300m
              memory: 320Mi
          env:
            # APP
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-redis-consumer-configmap
                  key: kafka_brokers
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-redis-consumer-configmap
                  key: kafka_consumer_group_id
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-redis-consumer-configmap
                  key: kafka_topic
            - name: REDIS_WATCHED_KEY
              valueFrom:
                configMapKeyRef:
                  name: kafka-redis-consumer-configmap
                  key: redis_watched_key
            # REDIS
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-redis-consumer-configmap
                  key: redis_port
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: redis_password
            # POSTGRES
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_uri
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_user
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: kafka-redis-consumer-secrets
                  key: postgres_port
          ports:
            - containerPort: 80
      restartPolicy: Always
---
# kafka-redis-consumer SERVICES
apiVersion: v1
kind: Service
metadata:
  name: kafka-redis-consumer-service
spec:
  selector:
    tier: kafka-redis-consumer
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
---

