# apiVersion: v1
# kind: Namespace
# metadata:
#   name: postgres-operator-system
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: pod-env-overrides
#   namespace: postgres-operator-system
# data:
#   # Any env variable used by spilo can be added
#   USE_WALG_BACKUP: "true"
#   USE_WALG_RESTORE: "true"
#   CLONE_USE_WALG_RESTORE: "true"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: psql-wale-creds
#   namespace: postgres-operator-system
# type: Opaque
# stringData:
#   key.json: |-
#     {"type":"service_account","project_id":"healthy-sign-374307","private_key_id":"28862500cccd531c63018c29abd8ff361720e1c3","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDM1n5k3+Ma2Rid\nIf+1w29CCEZlwOHWNF18lSJn1hWi3NogBZxZh5971khAacFfAVwI6udPCmi02zd8\n98CQB/PSNVJ17s6jpuVJ/WRlxD3RUuAlXsXZeSe2MonHkwqFueIqjeSBPH/ewgpK\ncntr5GLjubqGTBQv342hDSy6e4t2fb0RgkijkGmUqZD8zsjlRd58QCTx7ez1evVi\nv2Nh3+yYxy8X7x46iBlRJF1Bkji809SjhyxN2NCGpyzQJlY0cpLyC2pWzO6HG36m\n3aKBDWNCkO/RWyeRgUrpd37ojgBtvc1UuqviWirBXk92R5GFlHZbpT1RiHCGvXop\nuvUDxDwRAgMBAAECggEAYxxNn8Vsf2sXq7/tmCbtyEd0uHsxSpGfwk3ujctaQKkX\nqXLNicxDcInn/7Kr66oeu/nc3bOtogSHvqGpvIb8hHNkaMeZmDmCq+A9GbhwKL4u\n0iYfGPC0NEYTwEr3RmkAc5KgQ5/gRwogLJFkAnpJFuKgy6Y4Bknmn0xengR1IGks\nv5SEQeUAJ58aSiN6TuIfN3nz1wHJyoeew3KtnAGE/9VOsF/u/sYV8DDtinBIpT6U\n1P1nOd1ak4z9wSjqTD/yJc3Bzrws/lI2H8SIi0gUARhYBusBWcA2nhh1ZL8E8AmC\nwEhAyGdZFAw92Qn1hQlLe/Mx4QIrrp+rErjhQi7LOQKBgQDsqmd8Jzuzf8o+NcBF\nCHQ7nMKiEbDzGlyOuB3bnnZmS4C1roejof7sqIwI8yfKoEompSR2+y9GpX38e6Gd\n0IWJEhHMP7woh8L7fvlUBsUP1rj3Zejpwu2hWEPQpellMaZqabvuav9xKDC+QVzW\nAU8mS94y9or/PMb2Btj0q/B6bwKBgQDdknKF6CE4YJrIbQKxPzou0QOD3oeZDl83\n1WQVw8ZC0MCZ0eoTUXeV2YLr5KR/7Lf4dslt8ianJUDhjQ62DkzMmgOI1mpvqLYD\nGXfEt/0fPjYYK1poRAM24JnPcou6OiZxznj5r80HbbORAKtBu6mHXm/aByAmzKw2\nlRHsfZvxfwKBgQCjWRJIPQQV5pP+0Da+7xDavF4SYseRY5aS4z2ogf0SqfZSb/4q\n0PsU+Vh+LOZAEtZbSgybGtAMoNkOVX69YFlqvFAQe8Uw7FOGJqOMfYeyYPAVwf86\nqVI+1J8p+fnX4KcON6CA9NUOk0DhcFfVVd39fswEvOo/NQHWee9xIOPAfQKBgQC5\n+m94KESiDqw86QsmfXy3ySbbLBDDDsYrlkig4Cfs802GjySbvHjU5bK3j73nxmkQ\n+5vNVkDNcT6JU53ygAREhE3NMLQ8Lu8/oMPf8dNbwxsipFkJRXUxPcq8zlesI50b\nT4RJiB9fSdw8LMSSsxL0FfdqmSqKhqdSVUOrLi+TvwKBgF27Og+mnk/TKzRJKOqS\nXg1I07ombaNYYQJngp91e3iGF8bL48Fd2e00v2AD4O1TH08dC+P5rpWqtsiKmpgJ\nqn4oO+kelkWreIAPNBSoheiwTM+jwDYpL0TH+zyaBVmrNcmDTezHvNQAQdECHxu/\n7vE+oL/4riygRNqjH1OHDfa2\n-----END PRIVATE KEY-----\n","client_email":"942038068121-compute@developer.gserviceaccount.com","client_id":"110099918261558717204","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/942038068121-compute%40developer.gserviceaccount.com"}
