---
redisCluster:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  image: quay.io/opstree/redis
  tag: v7.0.5
  imagePullPolicy: IfNotPresent
  redisSecret:
    secretName: redis-secret
    secretKey: password
  leader:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
  follower:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
  resources: {}

pdb:
  enabled: false
  maxUnavailable: 1

externalConfig:
  enabled: false
  data: |
    tcp-keepalive 400
    slowlog-max-len 158
    stream-node-max-bytes 2048

externalService:
  enabled: false
  serviceType: LoadBalancer
  port: 6379

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources: {}

sidecars: []

nodeSelector: {}

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

securityContext:
  runAsUser: 1000
  fsGroup: 1000

affinity: {}
