# result ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: result-configmap
data:
  server_port: "80"
---
# result ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: result-secrets
data:
  # postgres://root:dgwjWYtiuXeaRFTmMlxOTrEVyKK8XCKK8dYUUwd3yBQplVwlrWq2W56tp1JX37sG@epitech-postgresql.postgres-operator-system.svc.cluster.local/postgres
  postgres_uri: cG9zdGdyZXM6Ly9yb290OmRnd2pXWXRpdVhlYVJGVG1NbHhPVHJFVnlLSzhYQ0tLOGRZVVV3ZDN5QlFwbFZ3bHJXcTJXNTZ0cDFKWDM3c0dAZXBpdGVjaC1wb3N0Z3Jlc3FsLnBvc3RncmVzLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbC9wb3N0Z3Jlcw==
  # root
  postgres_user: cm9vdA==
  # epitech-postgresql.postgres-operator-system.svc.cluster.local
  postgres_host: ZXBpdGVjaC1wb3N0Z3Jlc3FsLnBvc3RncmVzLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  # postgres
  postgres_db: cG9zdGdyZXM=
  # dgwjWYtiuXeaRFTmMlxOTrEVyKK8XCKK8dYUUwd3yBQplVwlrWq2W56tp1JX37sG
  postgres_password: ZGd3aldZdGl1WGVhUkZUbU1seE9UckVWeUtLOFhDS0s4ZFlVVXdkM3lCUXBsVndscldxMlc1NnRwMUpYMzdzRw==
  # 5432
  postgres_port: NTQzMg==
---
# result DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    tier: result
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      tier: result
  template:
    metadata:
      labels:
        tier: result
    spec:
      containers:
        - name: result
          image: ttl.sh/dc950c01-50aa-4578-8096-8d399ec69f51:24h
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 300m
              memory: 320Mi
          env:
            # APP
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: result-configmap
                  key: server_port
            # POSTGRES
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_uri
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_user
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: result-secrets
                  key: postgres_port
          ports:
            - containerPort: 80

      restartPolicy: Always
---
# result SERVICES
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    tier: result
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
